export const sellerInherited = [
  {
    id: 1,
    email: 'jamubupuji@email.com',
    password: 'sellerdummy',
    address: 'Lontar, Sambikerep, Surabaya, East Java, Java, 60217, Indonesia',
    isSeller: true,
    latitude: '-7.283733',
    longitude: '112.6585651',
  },
  {
    id: 2,
    email: 'siomaybatagorbandungmangenci@email.com',
    password: 'sellerdummy',
    address:
      'Jalan Yos Sudarso, Medaeng, Waru, Sidoarjo, East Java, Java, 61256, Indonesia',
    isSeller: true,
    latitude: '-7.35428',
    longitude: '112.7186239',
  },
  {
    id: 3,
    email: 'erhayajuice@email.com',
    password: 'sellerdummy',
    address: 'Geluran, Taman, Sidoarjo, East Java, Java, 60221, Indonesia',
    isSeller: true,
    latitude: '-7.3642594',
    longitude: '112.6945488',
  },
  {
    id: 4,
    email: 'idolaesdegan@email.com',
    password: 'sellerdummy',
    address: 'Geluran, Taman, Sidoarjo, East Java, Java, 60221, Indonesia',
    isSeller: true,
    latitude: '-7.3590949',
    longitude: '112.6889627',
  },
  {
    id: 5,
    email: 'gado-gadohandayani@email.com',
    password: 'sellerdummy',
    address:
      'Jalan Pacar Keling III, RW 06, Pacar Keling, Tambaksari, Surabaya, East Java, Java, 60131, Indonesia',
    isSeller: true,
    latitude: '-7.2579343',
    longitude: '112.7591321',
  },
  {
    id: 6,
    email: 'espisangijoassipa354@email.com',
    password: 'sellerdummy',
    address:
      'Jalan Dukuh Pakis VI A, RW 03, Dukuh Kupang, Dukuh Pakis, Surabaya, East Java, Java, 60225, Indonesia',
    isSeller: true,
    latitude: '-7.2862926',
    longitude: '112.7122421',
  },
  {
    id: 7,
    email: 'masakanpadangmustikajaya5@email.com',
    password: 'sellerdummy',
    address:
      'Jalan Graha Kebraon Mas Klumprik Cluster, RW 02, Balas Klumprik, Wiyung, Surabaya, East Java, Java, 60221, Indonesia',
    isSeller: true,
    latitude: '-7.3321389',
    longitude: '112.6887049',
  },
  {
    id: 8,
    email: 'buburayamcitra@email.com',
    password: 'sellerdummy',
    address:
      'Jalan Letnan Jenderal S. Parman, Waru, Sidoarjo, East Java, Java, 61256, Indonesia',
    isSeller: true,
    latitude: '-7.3623124',
    longitude: '112.7290967',
  },
  {
    id: 9,
    email: 'nasibakartumbuh@email.com',
    password: 'sellerdummy',
    address:
      'Grand Aloha Regency, Wage, Taman, Sidoarjo, East Java, Java, 61256, Indonesia',
    isSeller: true,
    latitude: '-7.3639496',
    longitude: '112.709831',
  },
  {
    id: 10,
    email: 'jatayubakery@email.com',
    password: 'sellerdummy',
    address: 'Krian, Sidoarjo, East Java, Java, 61262, Indonesia',
    isSeller: true,
    latitude: '-7.409062',
    longitude: '112.5776366',
  },
  {
    id: 11,
    email: 'amartasalad@email.com',
    password: 'sellerdummy',
    address: 'Katimoho, Gresik, East Java, Java, Indonesia',
    isSeller: true,
    latitude: '-7.3171519',
    longitude: '112.560987',
  },
  {
    id: 12,
    email: 'lontongsayurpakkumis@email.com',
    password: 'sellerdummy',
    address:
      'Jalan Siwalankerto Timur 1, RW 05, SiwalanKerto, Wonocolo, Surabaya, East Java, Java, 60236, Indonesia',
    isSeller: true,
    latitude: '-7.3382539',
    longitude: '112.7410942',
  },
  {
    id: 13,
    email: 'lemperlinda@email.com',
    password: 'sellerdummy',
    address:
      'Jalan Palem Selatan I, Pondok Tjandra Indah, Wadungasri, Waru, Sidoarjo, East Java, Java, 60293, Indonesia',
    isSeller: true,
    latitude: '-7.3418929',
    longitude: '112.77034',
  },
  {
    id: 14,
    email: 'irmaklepon@email.com',
    password: 'sellerdummy',
    address: 'Kedungturi, Taman, Sidoarjo, East Java, Java, 60221, Indonesia',
    isSeller: true,
    latitude: '-7.3606189',
    longitude: '112.6991742',
  },
  {
    id: 15,
    email: 'aselseafood@email.com',
    password: 'sellerdummy',
    address: 'Sekardangan, Sidoarjo, East Java, Java, Indonesia',
    isSeller: true,
    latitude: '-7.4640391',
    longitude: '112.7277195',
  },
];
